# Generated by Django 2.1.7 on 2019-04-21 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190421_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commen',
        ),
    ]
